"""Guard: codex/AGENTS.md must stay in sync with its canonical sources.

The Codex build is generated by build-codex-agents.py from root AGENTS.md (governance) +
SKILL.md (procedure). This test runs the builder's `--check` mode so a stale or
hand-edited codex/AGENTS.md — or a source reword that breaks a transform anchor — fails CI.
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILDER = ROOT / "build-codex-agents.py"


def test_codex_agents_is_up_to_date():
    if not BUILDER.is_file():
        import pytest
        pytest.skip("build-codex-agents.py not present")
    proc = subprocess.run([sys.executable, str(BUILDER), "--check"],
                          capture_output=True, text=True, cwd=str(ROOT))
    assert proc.returncode == 0, (
        f"codex/AGENTS.md is stale or the build failed — run "
        f"`python build-codex-agents.py`.\n{proc.stdout}\n{proc.stderr}")
